### ISSUE TITLE
Convert Integrated Library To Database Library

### ISSUE THREAD

**Issue by NickTrush** [gardarica/AltiumLibrary#3]
Hello!

First, I want to thank you for your lessons on YouTube. And the provided component library.
Thank you very much!!!

I would like to propose transferring these files of the integrated library to the database, as this is a more modern approach to Altium Designer. Actually for this there is even a corresponding tool in the program itself. 

https://www.altium.com/documentation/altium-designer/database-library-migration-tools-ad?version=18.1

**Comment by Nordic-Energy** [comment]
Hi! You can do a new fork fot the library and transformering her in the database. 

I use my library only in the integrated  form because I work alone. The database form more comfortable, when your are work in the team with 2+ hardware engineer or you have a many components.

I have a old library in the database form, I can send her for you on the email, if you interesting.

**Comment by gardarica** [comment]
Thank! Issues closed.
